### PR TITLE
fix: different game length between cutechess and fastchess

### PR DESCRIPTION
**Pull request by gahtan-syarif**
fix https://github.com/Disservin/fast-chess/issues/577

### CODE REVIEW

**Comment by gahtan-syarif** [comment]
this should fix it

**Comment by gahtan-syarif** [comment]
@vondele this should fix it

**Comment by Disservin** [comment]
> @vondele this should fix it

no

**Comment by gahtan-syarif** [comment]
> > this should fix it
> 
> no

it does, it fixed the game from adjudicating one ply late

**Comment by Disservin** [comment]
ah wait had the wrong book whops

**Pull request closed without merging**
