### PR TITLE
fix: indefinite wait for bestmove after time loss

### LINKED ISSUE #231: Tournament doesnt end if time losses happen
It seems that tournaments doesnt end when a time loss happened. i noticed it when i tested for 8 games, two of those games ended with time losses and when the tournament finished the 8th game, it just gets stuck there still calculating something (i know cuz my laptop fan doesnt wind down) and it doesnt finish the tournament and save to the config file as it usually does.

this is the command i inputted: fast-chess.exe -engine cmd=berserk-13.exe name=Engine1 -engine cmd=Stockfish-dev-20240411-249eec67.exe name=Engine2 -each tc=10+0.1 -rounds 4 -concurrency 4 -report penta=false

### PR DESCRIPTION
**Pull request by Disservin**
fixes #231

### CODE REVIEW

**Comment by Disservin** [comment]
@gahtan-syarif i think this might fix it, if you could try it out :D

**Comment by gahtan-syarif** [comment]
@Disservin unfortunately it doesnt seem to fix it
like here 2 of my threads got stuck on an infinite loop and the tournament doesnt end:
[output.txt](https://github.com/Disservin/fast-chess/files/14983774/output.txt)
reverting this pr https://github.com/Disservin/fast-chess/commit/57d2d64b9557a9f322afaea438cb7b30adad5d68 fixed it though

**Comment by Disservin** [comment]
oh um dumb, that if should be negated
```cpp
        if (us.engine.outputIncludesBestmove()) {
            // wait for bestmove, indefinitely
            us.engine.readEngine("bestmove", 0ms);
        }
```

**Comment by Disservin** [comment]
okkay just pushed update

**Comment by gahtan-syarif** [comment]
> okkay just pushed update

alright, gonna try it out 👍

**Comment by gahtan-syarif** [comment]
btw i got  this compiler warning thought you should know:
src/engines/uci_engine.cpp:153:1: warning: control reaches end of non-void function [-Wreturn-type] 153 | }

**Comment by Disservin** [comment]
Yes I just saw that, pushed a fix

**Comment by gahtan-syarif** [comment]
@Disservin fixed it :D 
[output.txt](https://github.com/Disservin/fast-chess/files/14984103/output.txt)

**Pull request merged**
