### PR TITLE
fixed-time-control test for e2e

### PR DESCRIPTION
**Pull request by gahtan-syarif**

### CODE REVIEW

**Comment by Disservin** [comment]
can you maybe also check the time in the pgn, the current state is perhaps a bit useless

**Comment by gahtan-syarif** [comment]
u mean the pgnout output from the ci? how to do that?

**Comment by Disservin** [comment]
In the script check that the times in the pgn are what you expected ?

**Comment by gahtan-syarif** [comment]
hmm the random mover doesnt seem to have a time control logic, so this pr is useless

**Pull request closed without merging**
