### PR TITLE
test

### PR DESCRIPTION
**Pull request by gahtan-syarif**

### CODE REVIEW

**Comment by Disservin** [comment]
let me just write some tests :p

**Comment by gahtan-syarif** [comment]
> let me just write some tests :p

wait theres something off with the indexing, ill have to check some stuff first

**Comment by gahtan-syarif** [comment]
??????
Screenshot 2024-06-18 040231
how did the above one pass the check and the below one failed?? how is that even possible

**Comment by Disservin** [comment]
> ?????? Screenshot 2024-06-18 040231 how did the above one pass the check and the below one failed?? how is that even possible

because you are writing the test in a fucked up way :p 

`opening[i] = book[book.fetchId()];`

fetchId() is != i

but here you
```
        CHECK(book_vector[0] == "r1b1kb1r/1p2pppp/p1np4/q5B1/3NP1n1/2N4P/PPP2PP1/R2QKB1R w KQkq - 1 9");
        CHECK(opening[0].fen == "r1b1kb1r/1p2pppp/p1np4/q5B1/3NP1n1/2N4P/PPP2PP1/R2QKB1R w KQkq - 1 9");
```
access both at 0...

**Comment by gahtan-syarif** [comment]
Screenshot 2024-06-18 041121
turns out its cause of this, the opening index from the first test case carries over to the second test case

**Comment by Disservin** [comment]
ive added some tests https://github.com/Disservin/fast-chess/commit/4a0551160a30e9cbb3ec044a17441283110c8bdb

**Comment by gahtan-syarif** [comment]
ahh ok, will update

**Pull request closed without merging**
