### PR TITLE
add statically linked zlib for CI release builds

### PR DESCRIPTION
**Pull request by gahtan-syarif**
https://github.com/Disservin/fast-chess/issues/482

### CODE REVIEW

**Comment by Disservin** [comment]
did you test if this even works?

**Comment by gahtan-syarif** [comment]
> did you test if this even works?

yeah, compile works fine with static linking

**Comment by Disservin** [comment]
> yeah, compile works fine with static linking

in the CI environment..

**Comment by gahtan-syarif** [comment]
> > yeah, compile works fine with static linking
> 
> in the CI environment..

how do i do that? the artifacts CI is disabled

**Comment by Disservin** [comment]
> how do i do that? the artifacts CI is disabled

try it in your fork

**Comment by gahtan-syarif** [comment]
> > how do i do that? the artifacts CI is disabled
> 
> try it in your fork

it worked

Screenshot 2024-06-22 185348

**Comment by Disservin** [comment]
okay sorry, i think id like to avoid releasing binaries with zlib and the gzstream library for that, since it is lgpl and id prefer to have user compile that themself

**Pull request closed without merging**
