### PR TITLE
refactor: make timemargin applicable to individual engines

### PR DESCRIPTION
**Pull request by Disservin**

### CODE REVIEW

**Comment by Disservin** [comment]
@gahtan-syarif it isnt that difficult, is it?^^

**Comment by gahtan-syarif** [comment]
lol nvm what i said then :D

**Comment by gahtan-syarif** [comment]
btw i noticed the timemargin is no longer stored in the tournament_options header? where is it stored alongside all the other engine config options

**Comment by Disservin** [comment]
there are two main config objects, tournament and engine ones
https://github.com/Disservin/fast-chess/blob/master/src/main.cpp#L17

engineconfig is also in types see:
https://github.com/Disservin/fast-chess/blob/master/src/types/engine_config.hpp

**Pull request merged**
