### PR TITLE
refactor: get rid of validateEnginePath

### PR DESCRIPTION
**Pull request by gahtan-syarif**

### CODE REVIEW

**Comment by gahtan-syarif** [comment]
> id still like to have before hand cause and not later

the current way has problem where it will throw error when `dir=` is placed after `-each` instead of `-engine` , by placing it afterhand we ensure that the dir and cmd variables are already populated before validation

**Comment by Disservin** [comment]
> > id still like to have before hand cause and not later
> 
> the current way has problem where it will throw error when `dir=` is placed after `-each` instead of `-engine` , by placing it afterhand we ensure that the dir and cmd variables are already populated before validation

then move it into the sanitize part

**Comment by Disservin** [comment]
here https://github.com/Disservin/fast-chess/blob/master/app/src/config/sanitize.cpp

**Comment by gahtan-syarif** [comment]
done 👍 

> here https://github.com/Disservin/fast-chess/blob/master/app/src/config/sanitize.cpp

**Pull request merged**
