### PR TITLE
refactor: improve version name

### PR DESCRIPTION
**Pull request by gahtan-syarif**
same as stockfish

### CODE REVIEW

**Comment by Disservin** [comment]
i dont see a reason to do this

**Comment by gahtan-syarif** [comment]
> i dont see a reason to do this

it makes it less confusing, cuz the current version printed is 0.8.2 even though thats the last release, and you get inconsistency with the version output of the git version and the local version where the git version prints the full year while the local version prints the last two digits of the year, plus it just looks nicer this way

**Comment by Disservin** [comment]
i prefer to keep it the way it is

**Comment by gahtan-syarif** [comment]
> i prefer to keep it the way it is

but then how do we differentiate the stable releases from dev versions? cuz they both print alpha-0.8.2

**Pull request closed without merging**
