### PR TITLE
refactor: sleep in busy loop

### PR DESCRIPTION
**Pull request by Disservin**

### CODE REVIEW

**Comment by gahtan-syarif** [comment]
```c++
std::this_thread::sleep_for(std::chrono::seconds(1));
```
what does this line do?

**Comment by Disservin** [comment]
> ```c++
> std::this_thread::sleep_for(std::chrono::seconds(1));
> ```
> 
> what does this line do?
> 
> edit: apparently its supposed to add a delay between games? if so can we make this as an option instead and set the default as 0 like cutechess? https://github.com/cutechess/cutechess/blob/master/docs/cutechess-cli.6.txt#L242

no this is the mainthread which waits for the tournament to end

**Comment by Disservin** [comment]
what i dont get is why the ci is bugged out

**Comment by gahtan-syarif** [comment]
> > ```c++
> > std::this_thread::sleep_for(std::chrono::seconds(1));
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > what does this line do?
> > edit: apparently its supposed to add a delay between games? if so can we make this as an option instead and set the default as 0 like cutechess? https://github.com/cutechess/cutechess/blob/master/docs/cutechess-cli.6.txt#L242
> 
> no this is the mainthread which waits for the tournament to end

ahh ok

**Comment by gahtan-syarif** [comment]
> what i dont get is why the ci is bugged out

is it for this pr specifically?

**Comment by Disservin** [comment]
no and my last two commits on master

**Comment by gahtan-syarif** [comment]
> no and my last two commits on master

can you try merging this branch to latest master?

**Comment by gahtan-syarif** [comment]
works

**Pull request merged**
