### PR TITLE
make fast-chess spelling consistent

### PR DESCRIPTION
**Pull request by robertnurnberg**
I checked any hits on `grep -iRl --include=\*.{txt,md,c,cpp,py,h,hpp} --include=man "fastchess" .` and `find . -type f -iname '*fastchess*'`, leaving internal variable names unchanged.

For the (non)-capitalization of `Fast-chess` in `man` I checked output of `man man`.

This PR brings fast-chess itself in line with the consistent spelling in https://github.com/official-stockfish/fishtest/pull/2119.

### CODE REVIEW

**Comment by Disservin** [comment]
mh internally i think id still like to refer to it as fastchess, easier to type than ahving to add a hyphen in between

**Comment by Disservin** [comment]
but tbh i havent thought much about the name actually

**Comment by vondele** [comment]
not too late to change the name tbh. The hypen is indeed a bit annoying at times, it requires to use two different spellings in code.

**Comment by Disservin** [comment]
tbh i only later realized that there already exists an engine with this name https://github.com/thomasahle/fastchess, avoiding some confusion/ a more unique name would be nice :p

**Comment by robertnurnberg** [comment]
Are we open to completely new names as well then? Does a quickchess exist?

**Comment by gahtan-syarif** [comment]
I think for a complete rename we need to ask the opinions of PGG106 and Szil as well as primary authors

**Comment by Disservin** [comment]
i dont think ive ever asked them about the name, was rather something i forced upon them

**Comment by gahtan-syarif** [comment]
> i dont think ive ever asked them about the name, was rather something i forced upon them

Then they might have other ideas for the name in that case, could use their opinion as well :)

**Comment by gahtan-syarif** [comment]
PGG106 suggests frog-chess, he might be joking im unsure

**Comment by Disservin** [comment]
should name it mercury 

> Mercury is named after the messenger for their gods

afterall engines are godlike and we carry their message

**Comment by gahtan-syarif** [comment]
sounds good, the roman god mercury is known as being very fast

**Comment by vondele** [comment]
And not unrelated to chess https://en.wikipedia.org/wiki/Ca%C3%AFssa#Vida's_poem

**Comment by robertnurnberg** [comment]
Not to forget that another name for mercury (the element) is *quick*silver. :)

**Comment by robertnurnberg** [comment]
Anyway, if we go down that route and choose a new name, would it make sense to immediately transfer to a new repo under official-stockfish?

In the meantime, I will close this PR.

**Comment by Disservin** [comment]
I don't see myself moving it to the stockfish org tbh, as of now I'm maintaining it independently

**Comment by gahtan-syarif** [comment]
quicksilver sounds pretty cool

**Pull request closed without merging**
