### PR TITLE
refactor: truncate unused openings and add unit tests for validation

### PR DESCRIPTION
**Pull request by gahtan-syarif**
i added the unit tests as requested, pls merge 🙏

### CODE REVIEW

**Comment by gahtan-syarif** [comment]
@Disservin help, idk how to access the openings.epd file in the tests, this doesnt seem to cut it: https://github.com/gahtan-syarif/fast-chess/blob/reducemem6/tests/openings_test.cpp#L12

**Comment by gahtan-syarif** [comment]
> @Disservin help, idk how to access the openings.epd file in the tests, this doesnt seem to cut it: https://github.com/gahtan-syarif/fast-chess/blob/reducemem6/tests/openings_test.cpp#L12

nvm figured it out

**Comment by Disservin** [comment]
This test isn't exactly testing much.. you are calling `getEpdBook` which returns a copy of the internal vector and then you check if certain strings are at the exact position you want them to be. You should be testing it how it is also used in the code, meaning you create the book and then you call `fetchId` multiple times and you use the result of that to index the `OpeningBook` which you then assert

**Comment by gahtan-syarif** [comment]
> This test isn't exactly testing much.. you are calling `getEpdBook` which returns a copy of the internal vector and then you check if certain strings are at the exact position you want them to be. You should be testing it how it is used in the code, meaning you create the book and then you call `fetchId` multiple times and you use the result of that to index the `OpeningBook` which you then assert and you call fetch as often as the number of rounds which will be played. Also there are cases to cover,
> 
> 1. rounds < number of openings
> 2. rounds == number of openings
> 3. rounds > number of openings

alright, ill fix it

**Pull request closed without merging**
