### PR TITLE
fix: fastchess output for startpos

### PR DESCRIPTION
**Pull request by gahtan-syarif**

### CODE REVIEW

**Comment by Disservin** [comment]
mh just leave it empty?

**Comment by gahtan-syarif** [comment]
> mh just leave it empty?

looks kinda ugly ngl, extra comma and all:

Screenshot 2024-06-23 183045

i think it makes more sense to just put in startpos, so people know what opening is used

**Comment by Disservin** [comment]
well you can also rewrite it so that `, ` is not shown..

**Comment by gahtan-syarif** [comment]
> well you can also rewrite it so that `, ` is not shown..

well sure but that would complicate the code more than it needs to, i think just adding startpos is simpler and more informative

**Comment by Disservin** [comment]
well the field name is "book name", if no book is given, the name should be empty and not "startpos" as that is not the name of the book

**Comment by gahtan-syarif** [comment]
updated

**Comment by Disservin** [comment]
what? you still have "startpos"

**Comment by gahtan-syarif** [comment]
updated ver 2

**Pull request merged**
