### PR TITLE
chore: update man

### PR DESCRIPTION
**Pull request by gahtan-syarif**

### CODE REVIEW

**Comment by gahtan-syarif** [comment]
> ??

i think you wrote it the opposite way, stats=true keeps the stats while stats=false drops it

**Comment by Disservin** [comment]
no https://github.com/Disservin/fast-chess/blob/master/src/cli/cli.cpp#L474

**Comment by gahtan-syarif** [comment]
> no https://github.com/Disservin/fast-chess/blob/master/src/cli/cli.cpp#L474

yes, if you type in stats=false it drops the stats like the code you linked, while stats=true keeps it, and the default is it keeps it ive tested it

**Comment by Disservin** [comment]
oh sorry yea youre right

**Pull request merged**
