### PR TITLE
Add cutechess compatibility testing to CI

### PR DESCRIPTION
**Pull request by vondele**
basic testing checking that the finished game state matches, and the game ply count matches.

### CODE REVIEW

**Comment by vondele** [comment]
current failed CI is of course to be expected.

**Comment by vondele** [comment]
(i.e. issue https://github.com/Disservin/fast-chess/issues/577)

**Comment by gahtan-syarif** [comment]
```
< Finished game 50 (sf_2 vs sf_1): 1/2-1/2 {Draw by adjudication}
---
> Finished game 50 (sf_2 vs sf_1): 1/2-1/2 {Draw by 3-fold repetition}
162c162
< Finished game 162 (sf_2 vs sf_1): 1/2-1/2 {Draw by adjudication}
---
> Finished game 162 (sf_2 vs sf_1): 1/2-1/2 {Draw by 3-fold repetition}
```
both differences are 3-fold repetition, possibly because of this? https://github.com/Disservin/fast-chess/pull/375

**Comment by Disservin** [comment]
the old issue was fixed, judging by the new one, the priority is different i think

**Comment by gahtan-syarif** [comment]
so i guess for cutechess, i guess wins by gameover is prioritized over wins by adjudication while draws by adjudication is prioritized over draw by 3-fold?

**Comment by vondele** [comment]
On Linux the script will also run locally.... so might make it easier to see who outputs what.

**Comment by Disservin** [comment]
fc adjudicates a move too late it seems

cutechess
```
[Event "?"]
[Site "?"]
[Date "2024.07.15"]
[Round "25"]
[White "sf_2"]
[Black "sf_1"]
[Result "1/2-1/2"]
[BlackTimeControl "inf"]
[FEN "r1bqk2r/ppp1bppp/n4n2/3Pp1B1/4N3/P7/1PP1NPPP/R2QKB1R w KQkq - 0 1"]
[GameDuration "00:00:00"]
[GameEndTime "2024-07-15T21:08:35.591 CEST"]
[GameStartTime "2024-07-15T21:08:35.410 CEST"]
[PlyCount "76"]
[SetUp "1"]
[Termination "adjudication"]
[WhiteTimeControl "inf"]

1. Bxf6 {+1.11/8 0.007s} Bxf6 {-0.24/6 0.002s} 2. N2c3 {+0.90/8 0.005s}
O-O {-0.96/6 0.003s} 3. Bxa6 {+0.75/8 0.006s} bxa6 {+0.13/6 0.001s}
4. Nxf6+ {+0.76/8 0.008s} Qxf6 {-0.54/6 0.003s} 5. Qd2 {+1.34/8 0.006s}
Qb6 {-1.01/6 0.004s} 6. O-O-O {+1.20/8 0.005s} a5 {-1.12/6 0.002s}
7. Na4 {+1.73/8 0.003s} Qg6 {-1.46/6 0s} 8. f3 {+1.71/8 0.002s}
e4 {-1.75/6 0.001s} 9. Nc3 {+1.62/8 0.001s} exf3 {-1.36/6 0s}
10. gxf3 {+1.52/8 0.001s} Qb6 {-1.08/6 0s} 11. b3 {+1.45/8 0.001s}
Qf6 {-1.26/6 0.002s} 12. Qd4 {+1.48/8 0.001s} Qxf3 {-1.67/6 0.001s}
13. Rhg1 {+1.62/8 0.002s} f6 {-1.58/6 0s} 14. Nb5 {+2.02/8 0.001s}
Rf7 {-1.29/6 0s} 15. d6 {+1.52/8 0.002s} cxd6 {-0.94/6 0.001s}
16. Rg3 {+1.71/8 0.001s} Qc6 {-1.53/6 0.001s} 17. Nxd6 {+1.16/8 0.001s}
Rc7 {+0.01/6 0s} 18. Rd2 {+1.89/8 0.002s} Kf8 {-0.42/6 0.001s}
19. Re3 {+3.59/8 0.001s} Bd7 {+0.51/6 0s} 20. Qf4 {+1.60/8 0.001s}
Be8 {-0.75/6 0s} 21. Nb5 {+0.49/8 0.002s} Rd7 {+0.02/6 0s}
22. Nd4 {+0.43/8 0.002s} Qb7 {-0.40/6 0.001s} 23. Ne6+ {-0.09/8 0.007s}
Kg8 {-0.31/6 0s} 24. Rxd7 {+0.05/8 0.002s} Qxd7 {+0.07/6 0.001s}
25. Nc7 {+0.10/8 0.002s} Rd8 {-0.07/6 0.001s} 26. Nxe8 {-0.03/8 0.004s}
Rxe8 {-0.26/6 0.001s} 27. Qc4+ {-0.22/8 0.003s} Kf8 {-0.10/6 0.001s}
28. Rxe8+ {-0.26/8 0.001s} Qxe8 {+0.01/6 0s} 29. Qc5+ {0.00/8 0.001s}
Qe7 {+0.03/6 0s} 30. Qc8+ {-0.06/8 0.001s} Kf7 {+0.71/6 0s}
31. Qc4+ {0.00/8 0.001s} Qe6 {+0.14/6 0.001s} 32. Qc7+ {0.00/8 0.001s}
Kg6 {+0.01/6 0.001s} 33. Qg3+ {0.00/8 0.001s} Kh6 {0.00/6 0.001s}
34. Qh4+ {0.00/8 0s} Kg6 {0.00/6 0s} 35. Qg3+ {0.00/8 0.002s} Kf7 {0.00/6 0s}
36. Qc7+ {0.00/8 0s} Qe7 {0.00/6 0s} 37. Qc4+ {0.00/8 0s} Kf8 {0.00/6 0s}
38. Qc8+ {0.00/8 0s} Kf7 {0.00/6 0s, Draw by adjudication} 1/2-1/2
```

fc

```
[Event "Fast-Chess Tournament"]
[Site "?"]
[Date "2024.07.15"]
[Round "25"]
[White "sf_2"]
[Black "sf_1"]
[Result "1/2-1/2"]
[SetUp "1"]
[FEN "r1bqk2r/ppp1bppp/n4n2/3Pp1B1/4N3/P7/1PP1NPPP/R2QKB1R w KQkq - 0 1"]
[GameDuration "00:00:00"]
[GameStartTime "2024-07-15T21:08:47 +0200"]
[GameEndTime "2024-07-15T21:08:47 +0200"]
[PlyCount "77"]
[TimeControl "-"]

1. Bxf6 {+1.11/8, 0.002s} Bxf6 {-0.24/6, 0.000s} 2. N2c3 {+0.90/8, 0.003s}
O-O {-0.96/6, 0.000s} 3. Bxa6 {+0.75/8, 0.001s} bxa6 {+0.13/6, 0.000s}
4. Nxf6+ {+0.76/8, 0.000s} Qxf6 {-0.54/6, 0.000s} 5. Qd2 {+1.34/8, 0.001s}
Qb6 {-1.01/6, 0.002s} 6. O-O-O {+1.20/8, 0.001s} a5 {-1.12/6, 0.000s}
7. Na4 {+1.73/8, 0.000s} Qg6 {-1.46/6, 0.000s} 8. f3 {+1.71/8, 0.002s}
e4 {-1.75/6, 0.001s} 9. Nc3 {+1.62/8, 0.001s} exf3 {-1.36/6, 0.000s}
10. gxf3 {+1.52/8, 0.001s} Qb6 {-1.08/6, 0.000s} 11. b3 {+1.45/8, 0.000s}
Qf6 {-1.26/6, 0.001s} 12. Qd4 {+1.48/8, 0.001s} Qxf3 {-1.67/6, 0.000s}
13. Rhg1 {+1.62/8, 0.003s} f6 {-1.58/6, 0.000s} 14. Nb5 {+2.02/8, 0.001s}
Rf7 {-1.29/6, 0.000s} 15. d6 {+1.52/8, 0.003s} cxd6 {-0.94/6, 0.000s}
16. Rg3 {+1.71/8, 0.001s} Qc6 {-1.53/6, 0.001s} 17. Nxd6 {+1.16/8, 0.002s}
Rc7 {+0.01/6, 0.000s} 18. Rd2 {+1.89/8, 0.004s} Kf8 {-0.42/6, 0.000s}
19. Re3 {+3.59/8, 0.000s} Bd7 {+0.51/6, 0.000s} 20. Qf4 {+1.60/8, 0.000s}
Be8 {-0.75/6, 0.000s} 21. Nb5 {+0.49/8, 0.002s} Rd7 {+0.02/6, 0.000s}
22. Nd4 {+0.43/8, 0.002s} Qb7 {-0.40/6, 0.001s} 23. Ne6+ {-0.09/8, 0.007s}
Kg8 {-0.31/6, 0.000s} 24. Rxd7 {+0.05/8, 0.002s} Qxd7 {+0.07/6, 0.001s}
25. Nc7 {+0.10/8, 0.000s} Rd8 {-0.07/6, 0.002s} 26. Nxe8 {-0.03/8, 0.004s}
Rxe8 {-0.26/6, 0.000s} 27. Qc4+ {-0.22/8, 0.002s} Kf8 {-0.10/6, 0.000s}
28. Rxe8+ {-0.26/8, 0.001s} Qxe8 {+0.01/6, 0.000s} 29. Qc5+ {+0.00/8, 0.001s}
Qe7 {+0.03/6, 0.000s} 30. Qc8+ {-0.06/8, 0.001s} Kf7 {+0.71/6, 0.000s}
31. Qc4+ {+0.00/8, 0.000s} Qe6 {+0.14/6, 0.001s} 32. Qc7+ {+0.00/8, 0.000s}
Kg6 {+0.01/6, 0.000s} 33. Qg3+ {+0.00/8, 0.000s} Kh6 {+0.00/6, 0.000s}
34. Qh4+ {+0.00/8, 0.000s} Kg6 {+0.00/6, 0.000s} 35. Qg3+ {+0.00/8, 0.001s}
Kf7 {+0.00/6, 0.000s} 36. Qc7+ {+0.00/8, 0.000s} Qe7 {+0.00/6, 0.000s}
37. Qc4+ {+0.00/8, 0.000s} Kf8 {+0.00/6, 0.000s} 38. Qc8+ {+0.00/8, 0.000s}
Kf7 {+0.00/6, 0.000s} 39. Qc4+ {+0.00/8, 0.000s, Draw by 3-fold repetition} 1/2-1/2
```

**Comment by Disservin** [comment]
@vondele  my bash aint the greatest though is 
`if [[ $? ]]; then` correct?

locally i get this.. dont know why it goes into that if branch?
```
+ grep 'Finished game'
+ sort -n -k 3
+ diff ./cutechess-cli-out.finished ./fast-chess-out.finished
+ [[ -n 0 ]]
+ echo 'Finished games have different termination status'
Finished games have different termination status
+ exit 1
```

**Comment by vondele** [comment]
my mistake I think... will push a fix.

**Comment by Disservin** [comment]
ah `[[ $? ]];` check if it is non empty i think which is always true, needs `if [[ $? -ne 0 ]];` i think?

**Pull request merged**
