### PR TITLE
refactor: change "saved results." message to logger::trace (ci error can be ignored)

### PR DESCRIPTION
**Pull request by gahtan-syarif**
improve cutechess output compatibility

### CODE REVIEW

**Comment by Disservin** [comment]
you still need to fix the ci

**Comment by gahtan-syarif** [comment]
> you still need to fix the ci

I did, i deleted the test from the e2e, it meeds to be merged to take effect

**Comment by Disservin** [comment]
> > you still need to fix the ci
> 
> I did, i deleted the test from the e2e, it meeds to be merged to take effect

no lol, there are two assertions, you missed one

**Comment by gahtan-syarif** [comment]
> > > you still need to fix the ci
> > 
> > 
> > I did, i deleted the test from the e2e, it meeds to be merged to take effect
> 
> no lol, there are two assertions, you missed one

Ahh i see, fixed 👍

**Pull request merged**
