### PR TITLE
feat: add support for overtime format

### PR DESCRIPTION
**Pull request by gahtan-syarif**
complete TC format is now something like this: 40/60+0.6:20/10+0.1

already tested it, works great
satisfies issue https://github.com/Disservin/fast-chess/issues/332

### CODE REVIEW

**Comment by gahtan-syarif** [comment]
done

**Comment by gahtan-syarif** [comment]
done

**Comment by Disservin** [comment]
well mh i dont like the added complexity and given that no one really uses movestogo anyway..

**Comment by gahtan-syarif** [comment]
> well mh i dont like the added complexity and given that no one really uses movestogo anyway..

i disagree, say if you want to emulate a FIDE tournament match
Screenshot_2024-04-12_030726
theres no way to do it in cutechess, with this patch fastchess offers that functionality.
also with this patch the TC now conforms to the PGN time control format
i think this patch would give us an edge over cutechess, same like penta sprt

**Comment by Disservin** [comment]
well sure but who does that anyway, the scope initially was to create something which is faster than cutechess and can be compiler more easily

the spec stuff can be it's own pr

**Comment by gahtan-syarif** [comment]
> well sure but who does that anyway, the scope initially was to create something which is faster than cutechess and can be compiler more easily
> 
> the spec stuff can be it's own pr

idk i think the complexity added isnt so much that its no longer understandable, plus its still backwards compatible with the old time format so i dont really see the problem,
yeah i guess this is first and foremost a cutechess alternative but if we can add new features and improve upon cutechess even further i dont see why not honestly, especially since we can now support the official FIDE time format with this feature

**Pull request closed without merging**
